Poc:
  Author: Lem
  Condition:
  Name:
  Vulnerability details: 
  Solutions:  
  method: post  # {get,post,put,delete}
  poc_url_path: '' 
  header:  
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8  
    User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 
    #Accept-Encoding: gzip, deflate
    #Accept-Language: zh-CN,zh;q=0.9
    #Cache-Control: max-age=0
    #Connection: keep-alive
    #Cookie: cookie
    #Host: www.baidu.com
  poc_files:  
    #file:  
     # - test.txt  
     # - hello  
  poc_post_data: ''  
  poc_json_data: ''  
  verification: 'response'   # '正则':'regex','响应包':'response','状态码':'status_code','json':'json'
  re_data_keyword: ''   # 响应包关键词
  regex_match: '(.+?)' #自定义正则匹配规则 r'r(.+?)l'
  status_code: 200